kind: ConfigMap
apiVersion: v1
metadata:
  name: marketer-admin
  labels:
    name: marketer-admin
    instance: marketer-admin
data:
  VERSION: "0.0.1"
  ORIGINS: "*,localhost:3000,cluster.tech1a.co:9021"
  MONGO_CONNECTION_STRING: "mongodb://root:root@mongo-marketer-headless.dev-marketer-db.svc.cluster.local:27017/"
  MONGO_DATABASE: "brokerage"
  SWAGGER_TITLE: "Marketer Admin"
  API_PREFIX: ""
  DOCS_URL: ""
  OPENAPI_URL: ""
  ROOT_PATH: ""
  SPLUNK_HOST: "172.24.65.206"
  SPLUNK_PORT: "5141"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketer-admin
spec:
  selector:
    matchLabels:
      app: marketer-admin
  replicas: 1
  template:
    metadata:
      labels:
        app: marketer-admin
    spec:
      containers:
      - name: marketer-admin
        image: "registry.tech1a.co:81/repository/tech1a-docker-registry/marketer-admin:latest"
        envFrom:
          - configMapRef:
              name: marketer-admin
        ports:
          - name: http
            containerPort: 8000
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: marketer-admin
  labels:
    app: marketer-admin
spec:
  type: ClusterIP
  selector:
    app: marketer-admin
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: marketer-admin
spec:
  ingressClassName: nginx
  rules:
    - host: devmarketer-admin.tech1a.co
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: marketer-admin
              port:
                number: 80
