kind: ConfigMap
apiVersion: v1
metadata:
  name: marketer-admin
  labels:
    name: marketer-admin
    instance: marketer-admin
data:
  ORIGINS: "*,localhost:3000,10.233.113.128,172.24.137.10:3000,cluster.tech1a.co:9021"
  MONGO_CONNECTION_STRING: "mongodb://root:3tliSqt3tDD5Bg@mongo-marketer-headless.stg-marketer-db.svc.cluster.local:27017/"
  MONGO_DATABASE: "brokerage"
  SWAGGER_TITLE: "Marketer Admin"
  API_PREFIX: ""
  DOCS_URL: ""
  OPENAPI_URL: ""
  ROOT_PATH: ""
  ISSUER: "https://cluster.tech1a.co"
  JWKS_CONFIGURATION_URL: "https://cluster.tech1a.co/.well-known/openid-configuration/jwks"
  SPLUNK_HOST: "log.tech1a.co"
  SPLUNK_PORT: "5142"
  FASTAPI_DOCS: ""
  FASTAPI_REDOC: ""
  TOKEN_URL: "https://cluster.tech1a.co/connect/token"
  CLIENT_ID: "M2M.RegisterServicePermission"
  CLIENT_SECRET: "IDPRegisterServicePermission"
  GRANT_TYPE: "client_credentials"
  OPENID_CONFIGURATION_URL: "https://cluster.tech1a.co/.well-known/openid-configuration"
  REGISTRATION_URL: "https://cluster.tech1a.co/api/service-permossion/register-service-permission"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketer-admin
spec:
  selector:
    matchLabels:
      app: marketer-admin
  replicas: 1
  template:
    metadata:
      labels:
        app: marketer-admin
    spec:
      containers:
      - name: marketer-admin
        image: "registry.tech1a.co:81/repository/tech1a-docker-registry/marketer-admin:latest"
        envFrom:
          - configMapRef:
              name: marketer-admin
        ports:
          - name: http
            containerPort: 8000
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: marketer-admin
  labels:
    app: marketer-admin
spec:
  type: ClusterIP
  selector:
    app: marketer-admin
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: marketer-admin
spec:
  ingressClassName: nginx
  rules:
    - host: stgmarketer-admin.tech1a.co
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: marketer-admin
              port:
                number: 80
