# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import src.protos.marketer_pb2 as marketer__pb2


class MarketerRPCServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllMarketers = channel.unary_unary(
                '/MarketerRPCService/GetAllMarketers',
                request_serializer=marketer__pb2.GetAllMarketersRPCRequest.SerializeToString,
                response_deserializer=marketer__pb2.ListGetMarketersRPCResponse.FromString,
                )
        self.GetMarketerById = channel.unary_unary(
                '/MarketerRPCService/GetMarketerById',
                request_serializer=marketer__pb2.GetMarketerByIdRPCRequest.SerializeToString,
                response_deserializer=marketer__pb2.GetMarketerByIdRPCResponse.FromString,
                )
        self.InsertMarketer = channel.unary_unary(
                '/MarketerRPCService/InsertMarketer',
                request_serializer=marketer__pb2.InsertMarketerRPCRequest.SerializeToString,
                response_deserializer=marketer__pb2.MarketerRPCResponse.FromString,
                )
        self.UpdateMarketer = channel.unary_unary(
                '/MarketerRPCService/UpdateMarketer',
                request_serializer=marketer__pb2.UpdateMarketerRPCRequest.SerializeToString,
                response_deserializer=marketer__pb2.MarketerRPCResponse.FromString,
                )
        self.UpdateMarketerActivationStatus = channel.unary_unary(
                '/MarketerRPCService/UpdateMarketerActivationStatus',
                request_serializer=marketer__pb2.UpdateMarketerActivationStatusRPCRequest.SerializeToString,
                response_deserializer=marketer__pb2.MarketerRPCResponse.FromString,
                )
        self.CreateMarketerRefCode = channel.unary_unary(
                '/MarketerRPCService/CreateMarketerRefCode',
                request_serializer=marketer__pb2.CreateMarketerRefCodeRPCRequest.SerializeToString,
                response_deserializer=marketer__pb2.MarketerRPCResponse.FromString,
                )
        self.DeleteMarketer = channel.unary_unary(
                '/MarketerRPCService/DeleteMarketer',
                request_serializer=marketer__pb2.DeleteMarketerRPCRequest.SerializeToString,
                response_deserializer=marketer__pb2.MarketerRPCResponse.FromString,
                )
        self.SearchMarketer = channel.unary_unary(
                '/MarketerRPCService/SearchMarketer',
                request_serializer=marketer__pb2.SearchMarketerRPCRequest.SerializeToString,
                response_deserializer=marketer__pb2.SearchMarketerPagedRPCResponse.FromString,
                )
        self.GetMarketerUrl = channel.unary_unary(
                '/MarketerRPCService/GetMarketerUrl',
                request_serializer=marketer__pb2.GetMarketerUrlRPCRequest.SerializeToString,
                response_deserializer=marketer__pb2.GetMarketerUrlRPCResponse.FromString,
                )


class MarketerRPCServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllMarketers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMarketerById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertMarketer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMarketer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMarketerActivationStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMarketerRefCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMarketer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchMarketer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMarketerUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketerRPCServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllMarketers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllMarketers,
                    request_deserializer=marketer__pb2.GetAllMarketersRPCRequest.FromString,
                    response_serializer=marketer__pb2.ListGetMarketersRPCResponse.SerializeToString,
            ),
            'GetMarketerById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMarketerById,
                    request_deserializer=marketer__pb2.GetMarketerByIdRPCRequest.FromString,
                    response_serializer=marketer__pb2.GetMarketerByIdRPCResponse.SerializeToString,
            ),
            'InsertMarketer': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertMarketer,
                    request_deserializer=marketer__pb2.InsertMarketerRPCRequest.FromString,
                    response_serializer=marketer__pb2.MarketerRPCResponse.SerializeToString,
            ),
            'UpdateMarketer': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMarketer,
                    request_deserializer=marketer__pb2.UpdateMarketerRPCRequest.FromString,
                    response_serializer=marketer__pb2.MarketerRPCResponse.SerializeToString,
            ),
            'UpdateMarketerActivationStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMarketerActivationStatus,
                    request_deserializer=marketer__pb2.UpdateMarketerActivationStatusRPCRequest.FromString,
                    response_serializer=marketer__pb2.MarketerRPCResponse.SerializeToString,
            ),
            'CreateMarketerRefCode': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMarketerRefCode,
                    request_deserializer=marketer__pb2.CreateMarketerRefCodeRPCRequest.FromString,
                    response_serializer=marketer__pb2.MarketerRPCResponse.SerializeToString,
            ),
            'DeleteMarketer': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMarketer,
                    request_deserializer=marketer__pb2.DeleteMarketerRPCRequest.FromString,
                    response_serializer=marketer__pb2.MarketerRPCResponse.SerializeToString,
            ),
            'SearchMarketer': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchMarketer,
                    request_deserializer=marketer__pb2.SearchMarketerRPCRequest.FromString,
                    response_serializer=marketer__pb2.SearchMarketerPagedRPCResponse.SerializeToString,
            ),
            'GetMarketerUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMarketerUrl,
                    request_deserializer=marketer__pb2.GetMarketerUrlRPCRequest.FromString,
                    response_serializer=marketer__pb2.GetMarketerUrlRPCResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MarketerRPCService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MarketerRPCService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllMarketers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MarketerRPCService/GetAllMarketers',
            marketer__pb2.GetAllMarketersRPCRequest.SerializeToString,
            marketer__pb2.ListGetMarketersRPCResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMarketerById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MarketerRPCService/GetMarketerById',
            marketer__pb2.GetMarketerByIdRPCRequest.SerializeToString,
            marketer__pb2.GetMarketerByIdRPCResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InsertMarketer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MarketerRPCService/InsertMarketer',
            marketer__pb2.InsertMarketerRPCRequest.SerializeToString,
            marketer__pb2.MarketerRPCResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateMarketer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MarketerRPCService/UpdateMarketer',
            marketer__pb2.UpdateMarketerRPCRequest.SerializeToString,
            marketer__pb2.MarketerRPCResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateMarketerActivationStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MarketerRPCService/UpdateMarketerActivationStatus',
            marketer__pb2.UpdateMarketerActivationStatusRPCRequest.SerializeToString,
            marketer__pb2.MarketerRPCResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateMarketerRefCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MarketerRPCService/CreateMarketerRefCode',
            marketer__pb2.CreateMarketerRefCodeRPCRequest.SerializeToString,
            marketer__pb2.MarketerRPCResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteMarketer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MarketerRPCService/DeleteMarketer',
            marketer__pb2.DeleteMarketerRPCRequest.SerializeToString,
            marketer__pb2.MarketerRPCResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchMarketer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MarketerRPCService/SearchMarketer',
            marketer__pb2.SearchMarketerRPCRequest.SerializeToString,
            marketer__pb2.SearchMarketerPagedRPCResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMarketerUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MarketerRPCService/GetMarketerUrl',
            marketer__pb2.GetMarketerUrlRPCRequest.SerializeToString,
            marketer__pb2.GetMarketerUrlRPCResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
