kind: ConfigMap
apiVersion: v1
metadata:
  name: marketer-admin
  labels:
    name: marketer-admin
    instance: marketer-admin
data:
  VERSION: "0.0.1"
  ORIGINS: "*"
  MONGO_CONNECTION_STRING: "mongodb://root:1219S4OiIhSXPJmOGfmdlFlsQ121@mongo-marketer-headless.pro-marketer-db.svc.cluster.local:27017/"
  MONGO_DATABASE: "brokerage"
  SWAGGER_TITLE: "Marketer Admin"
  API_PREFIX: ""
  DOCS_URL: ""
  OPENAPI_URL: ""
  ROOT_PATH: ""
  ISSUER: "https://idp.tavanaco.ir"
  JWKS_CONFIGURATION_URL: "https://idp.tavanaco.ir/.well-known/openid-configuration/jwks"
  SPLUNK_HOST: "log.tech1a.co"
  SPLUNK_PORT: "6141"
  FASTAPI_DOCS: ""
  FASTAPI_REDOC: ""
  TOKEN_URL: "https://idp.tavanaco.ir/connect/token"
  CLIENT_ID: "M2M.RegisterServicePermission"
  CLIENT_SECRET: "IDPRegisterServicePermission"
  GRANT_TYPE: "client_credentials"
  OPENID_CONFIGURATION_URL: "https://idp.tavanaco.ir/.well-known/openid-configuration"
  REGISTRATION_URL: "https://idp.tavanaco.ir/api/service-permossion/register-service-permission"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketer-admin
spec:
  selector:
    matchLabels:
      app: marketer-admin
  replicas: 1
  template:
    metadata:
      labels:
        app: marketer-admin
    spec:
      containers:
      - name: marketer-admin
        image: "registry.tech1a.co:81/repository/tech1a-docker-registry/marketer-admin:latest"
        envFrom:
          - configMapRef:
              name: marketer-admin
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: marketer-admin
  labels:
    app: marketer-admin
spec:
  type: ClusterIP
  selector:
    app: marketer-admin
  ports:
    - port: 443
      protocol: TCP
      targetPort: 80
---         
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: marketer-admin
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - marketer-admin.tavanaco.ir
    secretName: tavanaco-ir
  rules:
    - host: marketer-admin.tavanaco.ir
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: marketer-admin
              port:
                number: 443


